name: doc-api
services:
  doc-api-service-1:
    build:
      context: ..
      dockerfile: Dockerfile
    image: doc-api-service:latest
    container_name: doc-api-service-1
    expose: # port hanya terlihat oleh container lain di network yang sama
      - "${DOC_API_SERVICE_1_CONT_PORT}"
    environment:
      APP_PORT: ${DOC_API_SERVICE_1_CONT_PORT}
      APP_ENV: ${APP_ENV}
      APP_NAME: ${DOC_API_SERVICE_1_NAME}
      WEB_PREFORK: ${WEB_PREFORK}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_SECRET_KEY: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      DATABASE_HOST: 192.168.122.7 # dari vm
      DATABASE_PORT: ${DATABASE_HOST_PORT} # pakai host karena dari vm
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DOC_API_SERVICE_DB}
      DATABASE_MAX_OPEN_CONNECTION: ${DATABASE_MAX_OPEN_CONNECTION}
      DATABASE_MAX_IDLE_CONNECTION: ${DATABASE_MAX_IDLE_CONNECTION}
      MINIO_ENDPOINT: 192.168.122.7:${MINIO_HOST_PORT} # dari vm
      MINIO_PUBLIC_URL: http://192.168.122.7:${MINIO_HOST_PORT} # pakai local
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${DOC_API_SERVICE_MINIO_BUCKET}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      REDIS_HOST: 192.168.122.7
      REDIS_PORT: ${REDIS_HOST_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - network-doc-api

networks:
  network-doc-api:
    driver: bridge
